# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChatGPTReturningUserTestsDialogueTone():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_chatGPTReturningUserTestsDialogueTone(self):
    self.driver.get("https://chatgpt.com/")
    self.driver.set_window_size(1103, 1150)
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p data-placeholder=\"Ask anything\" class=\"placeholder\"><br class=\"ProseMirror-trailingBreak\"></p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".placeholder").click()
    self.driver.find_element(By.CSS_SELECTOR, "p").click()
    self.driver.find_element(By.ID, "prompt-textarea").click()
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Oh wow, things are actually finally going really well for me!! I feel amazing!!</p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".dark\\3A bg-token-bg-elevated-primary").click()
    element = self.driver.find_element(By.ID, "composer-submit-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".placeholder").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-token-text-secondary:nth-child(3) > .flex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#prompt-textarea > p").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".min-w-9")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#prompt-textarea > p").click()
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I\'ve been trying to read more books this year. Getting through them slower than I\'d like but making progress. </p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>The proliferation of electric vehicles represents a notable shift in the global automotive industry.</p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
