# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChatGPTFirstTimeTestsDialogueTone():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_chatGPTFirstTimeTestsDialogueTone(self):
    self.driver.get("https://chatgpt.com/")
    self.driver.set_window_size(1564, 1150)
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p data-placeholder=\"Ask anything\" class=\"placeholder\"><br class=\"ProseMirror-trailingBreak\"></p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".placeholder").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".min-w-9")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I can\'t believe it — I just passed my driving test first time!! Honestly did NOT see that coming!</p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button use").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-token-text-secondary:nth-child(2) .icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".list-none:nth-child(1) > .group .truncate").click()
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Wait, so does the brain actually stop developing in your twenties or is that just a myth?</p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    time.sleep(5000)
    self.driver.find_element(By.CSS_SELECTOR, ".list-none:nth-child(1) > .group").click()
    self.driver.find_element(By.CSS_SELECTOR, ".placeholder").click()
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I have recently transitioned to a remote working arrangement and am currently in the process of adjusting to the new environment.</p>'}", element)
    self.driver.find_element(By.ID, "composer-submit-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    time.sleep(5000)
    self.driver.find_element(By.CSS_SELECTOR, ".list-none:nth-child(1) > .group").click()
    self.driver.find_element(By.CSS_SELECTOR, ".placeholder").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".min-w-9")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I just found out I got into my dream university!! I can\'t believe it, I\'m absolutely thrilled!!</p>'}", element)
    self.driver.find_element(By.ID, "composer-submit-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    time.sleep(5000)
    self.driver.find_element(By.CSS_SELECTOR, ".list-none:nth-child(1) > .group").click()
    self.driver.find_element(By.CSS_SELECTOR, ".placeholder").click()
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p data-placeholder=\"Ask anything\" class=\"placeholder\"><br class=\"ProseMirror-trailingBreak\"></p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".wcDTda_prosemirror-parent").click()
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>My dog passed away this morning. I\'ve had him for twelve years and I just feel completely lost right now.</p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button use").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button use")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    time.sleep(5000)
    self.driver.find_element(By.CSS_SELECTOR, ".list-none:nth-child(1) > .group").click()
    self.driver.find_element(By.CSS_SELECTOR, ".placeholder").click()
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I can\'t BELIEVE my project partner did absolutely nothing and now wants to take credit for all my work. I\'m so angry I can barely think straight.</p>'}", element)
    self.driver.find_element(By.ID, "composer-submit-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    time.sleep(5000)
    self.driver.find_element(By.CSS_SELECTOR, ".list-none:nth-child(1) > .group").click()
    self.driver.find_element(By.CSS_SELECTOR, ".placeholder").click()
    element = self.driver.find_element(By.ID, "prompt-textarea")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I just had the most infuriating experience at the DMV. Two hours of waiting and they told me I had the wrong documents. I\'m absolutely livid.</p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#composer-submit-button > .icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
