# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGoogleGeminiFirstTimeTestsHumanEmotionBeh():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_googleGeminiFirstTimeTestsHumanEmotionBeh(self):
    self.driver.get("https://gemini.google.com/app/0465ca3af5d757c6")
    self.driver.set_window_size(1103, 1151)
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Something pretty good happened today. I\'m feeling alright about it.</p>'}", element)
    time.sleep(15000)
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I finally finished my dissertation after months of stress! I feel SO relieved and happy right now!</p>'}", element)
    time.sleep(15000)
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I don\'t know, things just feel a bit off lately. I\'m not really sure why.</p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor").click()
    time.sleep(15000)
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>My friend moved away today. It\'s weird, the house feels quieter now.</p>'}", element)
  
