# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGoogleGeminiFirstTimeTestsDialogueTone():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_googleGeminiFirstTimeTestsDialogueTone(self):
    self.driver.get("https://gemini.google.com/app/0465ca3af5d757c6")
    self.driver.set_window_size(1103, 1151)
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Oh my gosh, I just got tickets to see my favorite band live!! I\'ve been trying to get these for months!!</p>'}", element)
    time.sleep(15000)
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p> Hey, I\'ve always wondered — how does Wi-Fi actually work? Like what\'s actually happening?</p>'}", element)
    time.sleep(15000)
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>So dude, do you think there\'s actually life on other planets? What\'s your take?</p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor").click()
    time.sleep(15000)
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I\'ve been getting into cooking lately. Made a pasta dish last night that actually turned out pretty well</p>'}", element)
  
