# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGoogleGeminiReturningTestsHumanEmoBeh():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_googleGeminiReturningTestsHumanEmoBeh(self):
    self.driver.get("https://gemini.google.com/app/0465ca3af5d757c6")
    self.driver.set_window_size(1103, 1151)
    time.sleep(15000)
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I have successfully obtained tickets to the upcoming musical event. This is a highly anticipated outcome.</p>'}", element)
    time.sleep(15000)
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p> Please provide an explanation of the mechanism by which photosynthesis converts light into energy.</p>'}", element)
    time.sleep(15000)
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I have recently commenced engagement with culinary preparation activities and have observed satisfactory outcomes.</p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor").click()
    time.sleep(15000)
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>I just got promoted at work!! I\'ve been working towards this for two years and I\'m so excited!!</p>'}", element)
  
